[project]
folders = ["Videos", "Images", "Audio", "Project", "Export", "Export/Thumb"] # List of folders to create (Separating an folder by '/' creates an sub-folder)
video-projects-folder = ["~", "Documents", "Evolução", "Videos"] # Default Projects Folder ('~' --> user folder)
file-name = "video_project.toml" # Video project file name

[default.path]
video-path = ["Export", "video.mp4"] # Video file to upload
thumb-path = ["Export", "Thumb", "thumb.png"] # Thumbnail to upload
